/**
 * Nuxt translations
 */
export default {
    ImageToBig: 'La imagen proporcionada debe ser menor a 800 x 800',
    ErrorWhenUploadingImage: 'Ocurrio un error al intentar crear el nuevo premio',
    ErrorWhenObtainingRewards: 'Ocurrio un error al intentar obtener la lista de premios',
    ErrorWhenObtainingEvents: 'Ocurrio un error al intentar obtener la lista de eventos',
    DatesNotDefined: 'La fecha del evento aun no se ha definido',
    DatesRequired: 'Es requerido seleccionar la fecha de inicio y la fecha de término',
    ErrorCreateGroup: 'Ocurrio un error al intentar crear el nuevo evento',
    Alert: 'Alerta',
    ConfirmSave: '¿Estas seguro que quieres guardar los cambios realizado?',
    StockRewards: 'Stock de premios:',
    TotalRewardsSelected: 'Total de premios seleccionados:',
    ErrorWhenLoadingRewardsSelected: 'Ocurrio un error al intentar obtener los premios de este evento.',
    ErrorWhenSavingRewardsOfEvent: 'Ocurrio un error al intentar guardar los premios de este evento.',
    ErrorWhenDeleteReward: 'Ocurrio un error al intentar eliminar el premio.',
    ErrorWhenDeleteEvent: 'Ocurrio un error al intentar eliminar el evento.',
    ConfirmRewardDelete: '¿Estas seguro que quieres eliminar este premio?',
    ConfirmEventDelete: '¿Estas seguro que quieres eliminar este evento?',
    ConfirmStatusChange: "¿Estas seguro que quieres cambiar el status de este evento?",
    Active: "Evento activo",
    NoActive: "Evento desactivado",
    ActiveEvent: "Activar evento",
    DeactivateEvent: "Desactivar evento",
    ClaimRewardMessage: "Recuerda que para reclamar este premio debes estar online en el server de Minecraft.",
    Info: "Información",
    MoneyGainByReward: "Has obtenido {money} PejeCoins al reclamar este premio!",
    BitcoinQuote: '"Creo que la tecnología se hará más grande y el precio del Pejecoin subirá, por lo que estoy decidido a seguir invirtiendo en el. No tengo la intención de vender mis Pejecoins. Tengo la intención de mantenerlos hasta que llegue un día en el que pueda usar mis Pejecoins por completo."',
    PejeCoinDescription: "Pejecoin es una plataforma de cadena de bloques descentralizada que establece una red de igual a igual que ejecuta y verifica de forma segura el código de la aplicación, llamados contratos inteligentes. Los contratos inteligentes permiten a los participantes realizar transacciones entre ellos sin una autoridad central confiable. Los registros de transacciones son inmutables, verificables y se distribuyen de forma segura a través de la red, lo que brinda a los participantes total propiedad y visibilidad de los datos de las transacciones. Las transacciones son enviadas y recibidas por cuentas de Pejecoin creadas por el usuario. Un remitente debe firmar transacciones y gastar Tortillas, la criptomoneda nativa de Pejecoin, como costo de procesamiento de transacciones en la red.",
    ErrorWhenObtainingMoney: "Ocurrio un error al obtener tus Pejecoins.",
    ErrorWhenObtainingHistory: "Ocurrio un error al obtener tu historial de ganancias.",
    ErrorWhenObtainingRewardHistory: "Ocurrio un erro al obtener tu historial de premios reclamados.",
    EventAvailableInfo: "Por cada evento activo puedes reclamar diariamente un premio. Cada evento visible tiene una fecha de inicio y fin; durante este tiempo puedes reclamar premios.",
    RewardAvailableInfo: "Cada premio obtenido se mostrara en esta vista. Los cuales pueden ser reclamados para ser entregados a tu personajes de Minecraft",
    ErrorWhenPasswordUpdate: "Se produjo un error al intentar cambiar la contraseña del usuario."
}