/**
 * Nuxt translations
 */
export default {
    AboutMoney: "¿Qué es el Pejecoin y como funciona?",
    Active: "Evento activo",
    ActiveEvent: "Activar evento",
    Admin: "Admin",
    Alert: 'Alerta',
    Amount: "Cantidad",
    BackHome: "Regresar al inicio",
    BitcoinQuote: '"Creo que la tecnología se hará más grande y el precio del Pejecoin subirá, por lo que estoy decidido a seguir invirtiendo en el. No tengo la intención de vender mis Pejecoins. Tengo la intención de mantenerlos hasta que llegue un día en el que pueda usar mis Pejecoins por completo."',
    Cancel: "Cancelar",
    Canceled: "Cancelado",
    ChangePassword: "Cambiar contraseña",
    Claim: "Reclamar",
    ClaimPrize: "Reclamar premio",
    ClaimRewardMessage: "Recuerda que para reclamar este premio debes estar online en el server de Minecraft.",
    ClickChest: "Presiona el cofre para recibir un premio.",
    Close: "Cerrar",
    CommandType: "Tipo de comando",
    Confirm: "Aceptar",
    ConfirmEventDelete: '¿Estas seguro que quieres eliminar este evento?',
    ConfirmNewPassword: "Confirma tu nueva contraseña",
    ConfirmPassword: "Confirmar contraseña",
    ConfirmRewardDelete: '¿Estas seguro que quieres eliminar este premio?',
    ConfirmSave: '¿Estas seguro que quieres guardar los cambios realizado?',
    ConfirmStatusChange: "¿Estas seguro que quieres cambiar el status de este evento?",
    Created: "Creado",
    CreateNewReward: "Crear nuevo premio",
    CurrentPassword: "Contraseña actual",
    CustomCommand: "Comando personalizado",
    DateObtain: "Fecha obtenido",
    DatesNotDefined: 'La fecha del evento aun no se ha definido',
    DatesRequired: 'Es requerido seleccionar la fecha de inicio y la fecha de término',
    DeactivateEvent: "Desactivar evento",
    Details: "Detalles",
    Duration: "Duración",
    Edit: "Editar",
    EditEvent: "Editar evento",
    EditReward: "Editar premio",
    EffectLevel: "Nivel de efecto",
    EffectType: "Tipo de efecto",
    EnterCurrentPassword: "Ingresa tu contraseña actual",
    EnterEmail: "Ingresa tu correo",
    EnterNewPassword: "Ingresa tu nueva contraseña",
    EnterPassword: "Ingresa tu contraseña",
    ErrorCreateGroup: 'Ocurrio un error al intentar crear el nuevo evento',
    ErrorWhenDeleteEvent: 'Ocurrio un error al intentar eliminar el evento.',
    ErrorWhenDeleteReward: 'Ocurrio un error al intentar eliminar el premio.',
    ErrorWhenEventDetails: "Ocurrio un error al intentar obtener los detalles del evento.",
    ErrorWhenGetReward: "Ocurrio un error al intentar obtener tu premio.",
    ErrorWhenLoadingRewardsSelected: 'Ocurrio un error al intentar obtener los premios de este evento.',
    ErrorWhenObtainingEvents: 'Ocurrio un error al intentar obtener la lista de eventos',
    ErrorWhenObtainingHistory: "Ocurrio un error al obtener tu historial de ganancias.",
    ErrorWhenObtainingMoney: "Ocurrio un error al obtener tus Pejecoins.",
    ErrorWhenObtainingRewardHistory: "Ocurrio un erro al obtener tu historial de premios reclamados.",
    ErrorWhenObtainingRewards: 'Ocurrio un error al intentar obtener la lista de premios',
    ErrorWhenObtainingUsersOnline: "Ocurrio un error al intentar obtener los usuarios online.",
    ErrorWhenPasswordUpdate: "Se produjo un error al intentar cambiar la contraseña de tu usuario.",
    ErrorWhenSavingRewardsOfEvent: 'Ocurrio un error al intentar guardar los premios de este evento.',
    ErrorWhenStatusEvent: "Ocurrio un error al intentar cambiar el status actual del evento.",
    ErrorWhenUploadingImage: 'Ocurrio un error al intentar crear el nuevo premio',
    ErrorWhenUserRewards: "Ocurrio un error al intentar obtener los premios de tu usuario.",
    EventAvailableInfo: "Por cada evento activo puedes reclamar diariamente un premio. Cada evento visible tiene una fecha de inicio y fin; durante este tiempo puedes reclamar premios.",
    EventDescription: "Descripción del evento",
    EventEndDate: "Fecha final del evento",
    EventFinished: "Event terminado",
    EventOver: "Evento concluido",
    EventRewards: "Premios disponibles del evento",
    Events: "Eventos",
    EventsAvailable: "Eventos disponibles",
    EventStartDate: "Fecha de inicio del evento",
    EventTitle: "Titulo del evento",
    EventType: "Tipo de evento",
    Finish: "Finalizar",
    Finished: "Finalizado",
    GetReward: "Obtener premio",
    Gift: "Regalar",
    GiftPrize: "Regalar premio",
    GiftTo: "Regalado a",
    History: "Historial",
    HistoryMoney: "Historial de tus Pejecoins",
    HistoryRewardsClaim: "Historial de premios reclamados",
    ImageToBig: 'La imagen proporcionada debe ser menor a 800 x 800',
    Info: "Información",
    KeepSession: "Mantener la sesión iniciada",
    Level: "Nivel",
    Loading: "Cargando",
    LoadingBlocks: "Cargando bloques",
    Login: "Login",
    LogOut: "Cerrar sesión",
    Manager: "Gestor",
    MinecraftAccount: "Cuenta de minecraft",
    MinecraftAccountHelper: "Para evitar errores asegurarte de escribir el nombre exacto de la cuenta de minecraft que utilizas",
    MinecraftAccountPlaceholder: "Nombre exacto de tu cuenta de minecraft",
    MoneyGainByReward: "Has obtenido {money} PejeCoins al reclamar este premio!",
    MoneyHistoryGift: "Gastaste {amount} Pejecoins al haber regalado un premio al usuario {user}",
    MoneyHistoryReward: "Obtuviste {amount} Pejecoins por haber reclamado el premio {title}",
    MoneyHistoryRoulette: "Gastaste {amount} Pejecoins en la rouleta por el premio {title}",
    Name: "Nombre",
    NewEvent: "Crear nuevo evento",
    NewPassword: "Contraseña nueva",
    NewReward: "Nuevo premio",
    NoActive: "Evento desactivado",
    NoInfoToShow: "No hay información para mostrar",
    NoUsersOnline: "No hay jugadores online en el servidor de Minecraft.",
    PasswordCheck: "La contraseña debe coincidir",
    Pause: "Pausar",
    Paused: "Pausado",
    PejeCoinDescription: "Pejecoin es una plataforma de cadena de bloques descentralizada que establece una red de igual a igual que ejecuta y verifica de forma segura el código de la aplicación, llamados contratos inteligentes. Los contratos inteligentes permiten a los participantes realizar transacciones entre ellos sin una autoridad central confiable. Los registros de transacciones son inmutables, verificables y se distribuyen de forma segura a través de la red, lo que brinda a los participantes total propiedad y visibilidad de los datos de las transacciones. Las transacciones son enviadas y recibidas por cuentas de Pejecoin creadas por el usuario. Un remitente debe firmar transacciones y gastar Tortillas, la criptomoneda nativa de Pejecoin, como costo de procesamiento de transacciones en la red.",
    Price: "Precio",
    Rare: "Rareza",
    Register: "Registro",
    Restart: "Reiniciar",
    RewardAlreadyClaim: "Premio diario reclamado",
    RewardAmount: "Cantidad a entregar",
    RewardAvailableInfo: "Cada premio obtenido se mostrara en esta vista. Los cuales pueden ser reclamados para ser entregados a tu personaje de Minecraft",
    RewardDescription: "Descripción del premio",
    RewardName: "Nombre clave del premio",
    Rewards: "Premios",
    RewardsAvailable: "Premios disponibles",
    RewardsLeft: "Premios restantes:",
    RewardsObtain: "Premios ganados",
    RewardTitle: "Titulo del premio",
    Roulette: "Ruleta",
    SaveChanges: "Guardar cambios",
    Settings: "Ajustes",
    Shop: "Tienda",
    Start: "Iniciar",
    Started: "Activo",
    StockRewards: 'Stock de premios:',
    Success: "Exito",
    SuccessLoginMessage: "Se creo el usuario exitosamente, contacte el administrador para que te proporcione la clave de acceso del usuario registrado",
    TimeLeft: "Tiempo restante:",
    TotalRewardsLeft: "Total de premios restantes:",
    TotalRewardsSelected: 'Total de premios seleccionados:',
    UnitTime: "Unidad de tiempo",
    UpdatePassword: "Actualizar contraseña",
    UploadImage: "Subir imagen",
    UsersOnline: "Usuarios online",
    UsersOnlineHelp: "Se puede regalar premios a cualquier usuario que se encuentre online en el server.",
}